version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: kuhaku-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3333:3333"
    networks:
      - kuhaku-network

  frontend:
    build:
      context: ./frontend
    container_name: kuhaku-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - kuhaku-network

networks:
  kuhaku-network:
    driver: bridge
